"""empty message

Revision ID: 088b6deda231
Revises: 4df920e2fe12
Create Date: 2019-10-25 12:37:49.323076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088b6deda231'
down_revision = '4df920e2fe12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    # ### end Alembic commands ###
