"""empty message

Revision ID: 36dd7dc817cd
Revises: 4b3de8a04bd7
Create Date: 2019-12-12 11:33:52.554358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dd7dc817cd'
down_revision = '4b3de8a04bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_for_make_config', sa.Column('gateway', sa.String(length=64), nullable=True))
    op.add_column('storage_for_make_config', sa.Column('mng_vlan', sa.Integer(), nullable=True))
    op.add_column('storage_for_make_config', sa.Column('netmask', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_for_make_config', 'netmask')
    op.drop_column('storage_for_make_config', 'mng_vlan')
    op.drop_column('storage_for_make_config', 'gateway')
    # ### end Alembic commands ###
