"""empty message

Revision ID: 4b3de8a04bd7
Revises: d72619d4958b
Create Date: 2019-12-12 10:51:25.951054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3de8a04bd7'
down_revision = 'd72619d4958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_for_make_config', sa.Column('PCV_group', sa.Integer(), nullable=True))
    op.drop_column('storage_for_make_config', 'PCV_range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_for_make_config', sa.Column('PCV_range', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('storage_for_make_config', 'PCV_group')
    # ### end Alembic commands ###
