"""empty message

Revision ID: 9335327f5f64
Revises: f2058b6701a3
Create Date: 2019-12-12 05:15:52.146472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9335327f5f64'
down_revision = 'f2058b6701a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switch_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('port_names', sa.String(length=256), nullable=False),
    sa.Column('firmware', sa.String(length=64), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_for_make_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mku_info_id', sa.Integer(), nullable=True),
    sa.Column('switch_model_id', sa.Integer(), nullable=True),
    sa.Column('ipaddress', sa.String(length=64), nullable=True),
    sa.Column('pppoe_ports', sa.String(length=64), nullable=True),
    sa.Column('vlan_character', sa.String(length=64), nullable=True),
    sa.Column('PCV_range', sa.String(length=64), nullable=True),
    sa.Column('pppoe_single_vlan', sa.Integer(), nullable=True),
    sa.Column('switches_ports', sa.String(length=64), nullable=True),
    sa.Column('switches_ports_vlans', sa.String(length=64), nullable=True),
    sa.Column('switches_ports_uplink', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mku_info_id'], ['mku_info.id'], ),
    sa.ForeignKeyConstraint(['switch_model_id'], ['switch_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_for_make_config')
    op.drop_table('switch_model')
    # ### end Alembic commands ###
