"""empty message

Revision ID: a07be1197c9d
Revises: 4b3b3484d5b6
Create Date: 2019-12-01 13:15:54.629932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07be1197c9d'
down_revision = '4b3b3484d5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('registration_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'registration_expire')
    # ### end Alembic commands ###
