"""empty message

Revision ID: aa7f9391fbe1
Revises: a07be1197c9d
Create Date: 2019-12-03 04:58:21.541532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7f9391fbe1'
down_revision = 'a07be1197c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('expired', sa.DateTime(), nullable=True))
    op.drop_column('registration', 'registration_expire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('registration_expire', sa.DATETIME(), nullable=True))
    op.drop_column('registration', 'expired')
    # ### end Alembic commands ###
