"""empty message

Revision ID: d72619d4958b
Revises: 9335327f5f64
Create Date: 2019-12-12 07:36:02.495394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72619d4958b'
down_revision = '9335327f5f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_for_make_config', sa.Column('step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_for_make_config', 'step')
    # ### end Alembic commands ###
