"""empty message

Revision ID: f2058b6701a3
Revises: aa7f9391fbe1
Create Date: 2019-12-08 04:19:04.597436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2058b6701a3'
down_revision = 'aa7f9391fbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mku_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=False),
    sa.Column('gateway', sa.String(length=64), nullable=False),
    sa.Column('mng_vlan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway'),
    sa.UniqueConstraint('network')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mku_info')
    # ### end Alembic commands ###
